[SETTING]
  LOG_FILE = "../log.log"
  [SETTING.TYPE]
    TXT=1
    IMG=2
    ANI=3
    VID=4
  [SETTING.NAME]
    TXT="複製文"
    IMG="圖片"
    ANI="動圖"
    VID="影片"

[API]
  [API.TG]
    TOKEN = "YOUR_TELEGRAM_API_TOKEN"
  [API.HF]
    TOKENs = [
        "YOUR_HUGGINGFACETOKEN1", 
        "YOUR_HUGGINGFACETOKEN2", 
    ]
    SUM_MODEL = "csebuetnlp/mT5_multilingual_XLSum"
    MT_MODEL = "Helsinki-NLP/opus-mt-en-zh" # not used, using google translation atm
[DB]
  DIR = "../HokTseBun_db"
  COLLECTION = "Copypasta"
  EXPORT_DIR = "../HokTseBunArchive"