[SETTING]
  LOG_FILE = "../log.log"

[API]
  [API.TG]
    TOKEN = "YOUR_TELEGRAM_API_TOKEN"
  [API.HF]
    TOKENs = [
        "YOUR_HUGGINGFACETOKEN1", 
        "YOUR_HUGGINGFACETOKEN2", 
    ]
    SUM_MODEL = "csebuetnlp/mT5_multilingual_XLSum"
    MT_MODEL = "Helsinki-NLP/opus-mt-en-zh" # not used, using google translation atm
[DB]
  DIR = "../HokTseBun_db"
  COLLECTION = "Copypasta"