FILE_LOCATION = "../HokSeBun_db"
SUMMARIZATION_LOCATION = "../HokSeBun_db/Sums"
LOG_FILE = "../log.log"
TELEGRAM_API_TOKEN = "YOUR_TELEGRAM_API_TOKEN"
HUGGINGFACE_TOKENs = ["YOUR_HUGGINGFACETOKEN",]
HUGGINGFACE_MODEL = "yihsuan/mt5_chinese_small" # any chinese summarizatino model should work