[SETTING]
  LOG_FILE = "../log.log"

[API]
  [API.TG]
    TOKEN = "YOUR_TELEGRAM_API_TOKEN"
  [API.HF]
    TOKENs = [
        "YOUR_HUGGINGFACETOKEN1", 
        "YOUR_HUGGINGFACETOKEN2", 
    ]
    MODEL = "csebuetnlp/mT5_multilingual_XLSum" # any chinese summarizatino model should work

[DB]
  DIR = "../HokSeBun_db"
  COLLECTION = "Copypasta"